image: jitsi/android:latest  # JDK 17 inside

before_script:
  - chmod +x ./gradlew

stages:
  - build

build_app:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
